# Generated by Django 4.2.29 on 2026-03-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
    ]
